# testing-tutorial
language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - coverage run -m unittest discover